definitions:
  controller.PersonalPage:
    properties:
      Songs:
        items:
          $ref: '#/definitions/models.Songs'
        type: array
      admire:
        items:
          $ref: '#/definitions/models.Admire'
        type: array
      avatar:
        type: string
      background:
        type: string
      more:
        type: string
      name:
        type: string
      requestSongs:
        items:
          $ref: '#/definitions/models.RequestSongs'
        type: array
      school:
        type: string
      setting1:
        type: integer
      setting2:
        type: integer
      setting3:
        type: integer
    type: object
  controller.Tag:
    properties:
      tag1:
        type: integer
      tag2:
        type: integer
      tag3:
        type: integer
      tag4:
        type: integer
      tag5:
        type: integer
      tag6:
        type: integer
      tag7:
        type: integer
    type: object
  controller.Token:
    properties:
      uptoken:
        type: string
    type: object
  e.ErrMsgResponse:
    properties:
      message:
        type: string
    type: object
  models.Admire:
    properties:
      from:
        type: string
      number:
        type: integer
      song:
        type: string
      time:
        type: string
    type: object
  models.RequestSongs:
    properties:
      song:
        type: string
      time:
        type: string
    type: object
  models.Songs:
    properties:
      from:
        type: string
      song:
        type: string
      time:
        type: string
    type: object
info:
  contact: {}
  description: 2020治愈系
  title: healing2020
  version: "1.0"
paths:
  /qiniu/token:
    get:
      description: 获取七牛的upToken
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Token'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrMsgResponse'
      tags:
      - qiniu
  /user:
    get:
      description: 个人页接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.PersonalPage'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrMsgResponse'
      tags:
      - perponalpage
    put:
      description: 更新用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/e.ErrMsgResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrMsgResponse'
      tags:
      - PutUserInf
  /user/hobby:
    get:
      description: 获取用户爱好
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Tag'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrMsgResponse'
      tags:
      - hobby
    post:
      description: 爱好选择接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/e.ErrMsgResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/e.ErrMsgResponse'
      tags:
      - hobby
swagger: "2.0"
