info:
  contact: {}
  description: 2020治愈系
  title: healing2020
  version: "1.0"
paths:
  /qiniu/token:
    get:
      description: 获取七牛的upToken
      produces:
      - application/json
      responses:
        "200":
          description: '{"upToken": "xxxxx"}'
          schema:
            type: string
        "403":
          description: '{"err": "false"}'
          schema:
            type: string
      tags:
      - qiniu
swagger: "2.0"
